// <auto-generated />
using System;
using LivroAberturasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LivroAberturasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331202628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LivroAberturasAPI.Models.Abertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FamiliaDeLances")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Aberturas");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adversario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorDasPecas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataDaPartida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VarianteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VarianteId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Precisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrosGraves")
                        .HasColumnType("integer");

                    b.Property<int>("LancesBrilhantes")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecisaoGeral")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique();

                    b.ToTable("Precisoes");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Variante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AberturaId")
                        .HasColumnType("integer");

                    b.Property<string>("LancesChave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AberturaId");

                    b.ToTable("Variantes");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Abertura", b =>
                {
                    b.HasOne("LivroAberturasAPI.Models.Usuario", "Usuario")
                        .WithMany("Aberturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Partida", b =>
                {
                    b.HasOne("LivroAberturasAPI.Models.Variante", "Variante")
                        .WithMany("Partidas")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Precisao", b =>
                {
                    b.HasOne("LivroAberturasAPI.Models.Partida", "Partida")
                        .WithOne("Precisao")
                        .HasForeignKey("LivroAberturasAPI.Models.Precisao", "PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Variante", b =>
                {
                    b.HasOne("LivroAberturasAPI.Models.Abertura", "Abertura")
                        .WithMany("Variantes")
                        .HasForeignKey("AberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abertura");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Abertura", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Partida", b =>
                {
                    b.Navigation("Precisao");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Usuario", b =>
                {
                    b.Navigation("Aberturas");
                });

            modelBuilder.Entity("LivroAberturasAPI.Models.Variante", b =>
                {
                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
